name: Build Windows, Linux, and macOS Executables with PyInstaller

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: hserver_windows
            zip_name: hserver_windows.zip
          - os: ubuntu-latest
            artifact_name: hserver_linux
            zip_name: hserver_linux.zip
          - os: macos-latest
            artifact_name: hserver_macos
            zip_name: hserver_macos.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
        shell: bash

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --log-level DEBUG ./main.spec
        shell: bash

      - name: list files in dist directory
        run: ls -l dist/

      - name: Zip OneDir folder (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path "dist/hserver" -DestinationPath "${{ matrix.zip_name }}"
        shell: pwsh

      - name: Zip OneDir folder (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: cd dist && zip -r ../${{ matrix.zip_name }} hserver/
        shell: bash

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.zip_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: hserver_windows
          path: ./

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: hserver_linux
          path: ./

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: hserver_macos
          path: ./

      - name: Create Release and Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hserver_windows.zip
            hserver_linux.zip
            hserver_macos.zip
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          body: Automated release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
